#######Makefile#######
#######Ex1#######
# all:teste_grafo

# teste_grafo: grafo.o
# 	gcc teste_grafo.c grafo.o -g -Wall

# grafo.o: grafo.c grafo.h
# 	gcc -c grafo.c -g -Wall

# clear:
# 	rm grafo.o

#######Ex2#######
all:teste_grafo2

teste_grafo2: grafo.o
	gcc teste_grafo2.c grafo.o -g -Wall

grafo.o: grafo.c grafo.h
	gcc -c grafo.c -g -Wall

clear:
	rm grafo.o